name: here_location_services
channels:
  - conda-forge
dependencies:
  - pip
  - xyzspaces
  - jupyterlab
  - shapely
  - here-map-widget-for-jupyter
  - pip:
    - "-r ../requirements.txt"
    - "-r ../requirements_dev.txt"
    - "-e ../"
